### ISSUE TITLE
Syntax & Undeclared Identifier Installation Errors

### ISSUE THREAD

**Issue by YakovlevMik** [dfujim/mudpy#5]
When attempting to install mud-py command prompt returns a mix of syntax (ex. C2143, C2059, C2146) and undeclared identifier (C2065) errors. The errors occur in both `\mud_src\mud.h` and `\mud_src\mud.c`. Command Prompt output attached as *.txt file

[mud-py_install_error.txt](https://github.com/dfujim/mudpy/files/6987044/mud-py_install_error.txt)

Installation performed via `pip install --user mud-py`, with all prior installations satisfied (machine has installed Visual Studio Build Tools 2019, as well as Visual Studio Community 2019); Python 3.9.6; pip 21.2.3

**Comment by dfujim** [comment]
Hi @YakovlevMik, unfortunately mudpy doesn't yet work on windows machines. Thanks for the output text though, that's useful! 

@djasnd: is there something extra needed to compile the mud source on windows machines?

**Comment by YakovlevMik** [comment]
Thank you @dfujim. Would mud-py work on Linux? or is it currently designed for Unix only?

**Comment by dfujim** [comment]
I have it working on Ubuntu 18.04, Ubuntu 20.04, CentOS Tumbleweed, and Scientific Linux; so I would expect it to work on most if not all linux distributions. It should also work on macOS, but I can say which versions.

**Comment by dfujim** [comment]
Looks good, except that the python install doesn't work yet. This seems to be related to the checks for `__MSDOS__` in `mud.h`. This shows as a `'bcopy' undefined` error, which is related to [these lines](https://github.com/dfujim/mudpy/blob/5f38a866abfcedfa993a3c982350943ebcd61ddc/mud_src/mud.h#L186-L189), but the check for `__MSDOS__` appears elsewhere as well (such as [here](https://github.com/dfujim/mudpy/blob/5f38a866abfcedfa993a3c982350943ebcd61ddc/mud_src/mud.h#L202) and [here](https://github.com/dfujim/mudpy/blob/5f38a866abfcedfa993a3c982350943ebcd61ddc/mud_src/mud.h#L429)). 

I had originally added the `__MSDOS__` flag to `setup.py` since that's what the old `Makefile.win` script was doing, but it may make more sense to just find/replace `__MSDOS__` for `_WIN32`. Both solutions allows for the pip installation on my machine. 

By the way, you can run the installation from your local files in two ways (both from the directory containing `setup.py`): 

- Through pip: `pip install --user -e .`
- Directly through the setup script: `python setup.py build_ext --inplace`

**Comment by dfujim** [comment]
See dc7e1657d6441b9555bb87bbf11c525460ab8ccf
